spring:
  datasource:
    url: jdbc:postgresql://localhost:${ORDERSERVICE_POSTGRES_PORT}/${ORDERSERVICE_POSTGRES_DB}

grpc:
  client:
    orderClientService:
      address: localhost:9090
      negotiation-type: PLAINTEXT